# Generated by Django 3.2.16 on 2023-01-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField()),
                ('s_id', models.IntegerField()),
                ('complaint', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'complaint',
                'managed': False,
            },
        ),
    ]
