# Generated by Django 3.2.16 on 2023-01-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=20)),
                ('s_id', models.IntegerField()),
                ('units_left', models.IntegerField()),
            ],
            options={
                'db_table': 'hub',
                'managed': False,
            },
        ),
    ]
