# Generated by Django 3.2.16 on 2023-01-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPoints',
            fields=[
                ('cp_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('u_id', models.IntegerField()),
                ('cpoint', models.IntegerField()),
            ],
            options={
                'db_table': 'c_points',
                'managed': False,
            },
        ),
    ]
