# Generated by Django 3.2.16 on 2023-01-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.AutoField(primary_key=True, serialize=False)),
                ('slot_time', models.CharField(max_length=20)),
                ('u_id', models.IntegerField()),
                ('slot_date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'slot',
                'managed': False,
            },
        ),
    ]
