# Generated by Django 3.2.16 on 2023-01-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('v_brand', models.CharField(max_length=20)),
                ('v_model', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vehicle',
                'managed': False,
            },
        ),
    ]
