# Generated by Django 3.2.16 on 2023-01-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRequest',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_id', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('dboy_id', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'd_request',
                'managed': False,
            },
        ),
    ]
