# Generated by Django 3.2.16 on 2023-01-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBoy',
            fields=[
                ('dboy_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_id', models.IntegerField()),
                ('w_id', models.IntegerField()),
                ('w_status', models.CharField(max_length=20)),
                ('dboy_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=45)),
                ('password', models.IntegerField()),
            ],
            options={
                'db_table': 'd_boy',
                'managed': False,
            },
        ),
    ]
